// <auto-generated />
using System;
using Arbitrage.WebApi.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arbitrage.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250809143347_ChangeCurrencyPair")]
    partial class ChangeCurrencyPair
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Arbitrage.Exchange.Domain.Entities.ExchangeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("Arbitrage.Graph.Domain.Candle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketType")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("SymbolId");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("Arbitrage.Symbols.Domain.Entities.CurrencyPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BaseCoinId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuoteCoinId")
                        .HasColumnType("TEXT");

                    b.Property<int>("exchangeType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCoinId");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("QuoteCoinId");

                    b.ToTable("CurrencyPairs");
                });

            modelBuilder.Entity("Arbitrage.Symbols.Domain.Entities.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("Arbitrage.Graph.Domain.Candle", b =>
                {
                    b.HasOne("Arbitrage.Exchange.Domain.Entities.ExchangeModel", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arbitrage.Symbols.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Arbitrage.Symbols.Domain.Entities.CurrencyPair", b =>
                {
                    b.HasOne("Arbitrage.Symbols.Domain.Entities.Symbol", "BaseCoin")
                        .WithMany()
                        .HasForeignKey("BaseCoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arbitrage.Exchange.Domain.Entities.ExchangeModel", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arbitrage.Symbols.Domain.Entities.Symbol", "QuoteCoin")
                        .WithMany()
                        .HasForeignKey("QuoteCoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCoin");

                    b.Navigation("Exchange");

                    b.Navigation("QuoteCoin");
                });
#pragma warning restore 612, 618
        }
    }
}
